// Vocabulary for the claims domain.
// Kept separate from consts.ts (activity log event names) to avoid clutter.

export const US_STATES = [
  { value: "AL", label: "Alabama" },
  { value: "AK", label: "Alaska" },
  { value: "AZ", label: "Arizona" },
  { value: "AR", label: "Arkansas" },
  { value: "CA", label: "California" },
  { value: "CO", label: "Colorado" },
  { value: "CT", label: "Connecticut" },
  { value: "DE", label: "Delaware" },
  { value: "DC", label: "District of Columbia" },
  { value: "FL", label: "Florida" },
  { value: "GA", label: "Georgia" },
  { value: "HI", label: "Hawaii" },
  { value: "ID", label: "Idaho" },
  { value: "IL", label: "Illinois" },
  { value: "IN", label: "Indiana" },
  { value: "IA", label: "Iowa" },
  { value: "KS", label: "Kansas" },
  { value: "KY", label: "Kentucky" },
  { value: "LA", label: "Louisiana" },
  { value: "ME", label: "Maine" },
  { value: "MD", label: "Maryland" },
  { value: "MA", label: "Massachusetts" },
  { value: "MI", label: "Michigan" },
  { value: "MN", label: "Minnesota" },
  { value: "MS", label: "Mississippi" },
  { value: "MO", label: "Missouri" },
  { value: "MT", label: "Montana" },
  { value: "NE", label: "Nebraska" },
  { value: "NV", label: "Nevada" },
  { value: "NH", label: "New Hampshire" },
  { value: "NJ", label: "New Jersey" },
  { value: "NM", label: "New Mexico" },
  { value: "NY", label: "New York" },
  { value: "NC", label: "North Carolina" },
  { value: "ND", label: "North Dakota" },
  { value: "OH", label: "Ohio" },
  { value: "OK", label: "Oklahoma" },
  { value: "OR", label: "Oregon" },
  { value: "PA", label: "Pennsylvania" },
  { value: "RI", label: "Rhode Island" },
  { value: "SC", label: "South Carolina" },
  { value: "SD", label: "South Dakota" },
  { value: "TN", label: "Tennessee" },
  { value: "TX", label: "Texas" },
  { value: "UT", label: "Utah" },
  { value: "VT", label: "Vermont" },
  { value: "VA", label: "Virginia" },
  { value: "WA", label: "Washington" },
  { value: "WV", label: "West Virginia" },
  { value: "WI", label: "Wisconsin" },
  { value: "WY", label: "Wyoming" },
] as const;

export const POLICY_TYPES = [
  { value: "HO3", label: "HO-3 (Homeowners — Special Form)" },
  { value: "HO5", label: "HO-5 (Homeowners — Comprehensive)" },
  { value: "HO6", label: "HO-6 (Condo Unit Owners)" },
  { value: "HO8", label: "HO-8 (Older Home)" },
  { value: "DP1", label: "DP-1 (Dwelling — Basic)" },
  { value: "DP3", label: "DP-3 (Dwelling — Special Form / Rental)" },
  { value: "Commercial", label: "Commercial Property" },
  { value: "BOP", label: "Business Owners (BOP)" },
  { value: "Flood-NFIP", label: "Flood (NFIP)" },
  { value: "Flood-Private", label: "Flood (Private)" },
  { value: "Wind", label: "Wind / Hurricane (separate)" },
  { value: "Auto", label: "Auto" },
  { value: "Other", label: "Other" },
] as const;

export const TYPE_OF_LOSS = [
  { value: "wind", label: "Wind" },
  { value: "hurricane", label: "Hurricane" },
  { value: "tornado", label: "Tornado" },
  { value: "hail", label: "Hail" },
  {
    value: "water_non_weather",
    label: "Water — non-weather (pipe burst, leak)",
  },
  { value: "water_weather", label: "Water — weather (rain/snow/storm)" },
  { value: "flood", label: "Flood" },
  { value: "fire", label: "Fire" },
  { value: "smoke", label: "Smoke" },
  { value: "lightning", label: "Lightning" },
  { value: "theft", label: "Theft / Vandalism" },
  { value: "mold", label: "Mold" },
  { value: "fallen_tree", label: "Fallen tree / object" },
  { value: "roof_leak", label: "Roof leak" },
  { value: "sinkhole", label: "Sinkhole" },
  { value: "earthquake", label: "Earthquake" },
  { value: "freeze", label: "Freeze / Burst" },
  { value: "other", label: "Other" },
] as const;

export const CLAIM_STATUSES = [
  { value: "intake", label: "Intake" },
  { value: "filed", label: "Claim Filed" },
  { value: "adjuster_assigned", label: "Adjuster Assigned" },
  { value: "inspection_scheduled", label: "Inspection Scheduled" },
  { value: "inspected", label: "Inspected" },
  { value: "estimate_pending", label: "Estimate Pending" },
  { value: "negotiation", label: "Negotiation" },
  { value: "partial_payment", label: "Partial Payment" },
  { value: "reopen", label: "Reopen / Supplemental" },
  { value: "denied", label: "Denied" },
  { value: "appraisal", label: "Appraisal" },
  { value: "mediation", label: "Mediation" },
  { value: "litigation", label: "Litigation" },
  { value: "settled", label: "Settled" },
  { value: "closed", label: "Closed" },
] as const;

export const SETTLEMENT_METHODS = [
  { value: "negotiation", label: "Negotiation" },
  { value: "appraisal", label: "Appraisal" },
  { value: "mediation", label: "Mediation" },
  { value: "litigation", label: "Litigation" },
  { value: "denied", label: "Denied" },
  { value: "withdrawn", label: "Withdrawn" },
] as const;

export const PA_FIRM_ROLES = [
  { value: "lead_pa", label: "Lead public adjuster" },
  { value: "co_with_attorney", label: "Co-handled with attorney" },
  { value: "handed_to_attorney", label: "Handed to attorney" },
  { value: "reinspection_only", label: "Re-inspection only" },
] as const;

export const ESTIMATE_SOURCES = [
  { value: "carrier", label: "Carrier" },
  { value: "public_adjuster", label: "Public Adjuster (us)" },
  { value: "contractor", label: "Contractor" },
  { value: "engineer", label: "Engineer" },
  { value: "other", label: "Other" },
] as const;

export const CARRIER_ADJUSTER_ROLES = [
  { value: "staff", label: "Staff" },
  { value: "independent", label: "Independent (IA)" },
  { value: "desk", label: "Desk adjuster" },
  { value: "field", label: "Field adjuster" },
  { value: "reinspector", label: "Re-inspector" },
  { value: "supervisor", label: "Supervisor" },
] as const;
