--
-- Tables
-- This file declares all tables in the public schema.
--

-- Extensions
create extension if not exists "http" with schema "extensions";
create extension if not exists "citext" with schema "extensions";

-- Private schema (used by sales policies migration)
create schema if not exists "private";

create table public.companies (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    name text not null,
    sector text,
    size smallint,
    linkedin_url text,
    website extensions.citext,
    phone_number text,
    address text,
    zipcode text,
    city text,
    state_abbr text,
    sales_id bigint,
    context_links json,
    country text,
    description text,
    revenue text,
    tax_identifier text,
    logo jsonb
);

create table public.contacts (
    id bigint generated by default as identity primary key,
    first_name text,
    last_name text,
    gender text,
    title text,
    background text,
    avatar jsonb,
    first_seen timestamp with time zone,
    last_seen timestamp with time zone,
    has_newsletter boolean,
    status text,
    tags bigint[],
    company_id bigint,
    sales_id bigint,
    linkedin_url text,
    email_jsonb jsonb,
    phone_jsonb jsonb
);

create table public.contact_notes (
    id bigint generated by default as identity (sequence name public."contactNotes_id_seq") not null,
    contact_id bigint not null,
    text text,
    date timestamp with time zone default now(),
    sales_id bigint,
    status text,
    attachments jsonb[]
);

create table public.deals (
    id bigint generated by default as identity primary key,
    name text not null,
    company_id bigint,
    contact_ids bigint[],
    category text,
    stage text not null,
    description text,
    amount bigint,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    archived_at timestamp with time zone,
    expected_closing_date date,
    sales_id bigint,
    index smallint
);

create table public.deal_notes (
    id bigint generated by default as identity (sequence name public."dealNotes_id_seq") not null,
    deal_id bigint not null,
    type text,
    text text,
    date timestamp with time zone default now(),
    sales_id bigint,
    attachments jsonb[]
);

create table public.sales (
    id bigint generated by default as identity primary key,
    first_name text not null default 'Pending'::text,
    last_name text not null default 'Pending'::text,
    email extensions.citext not null,
    administrator boolean not null,
    user_id uuid not null,
    avatar jsonb,
    disabled boolean not null default false
);

create unique index uq__sales__user_id on public.sales using btree (user_id);

create table public.tags (
    id bigint generated by default as identity primary key,
    name text not null,
    color text not null
);

create table public.tasks (
    id bigint generated by default as identity primary key,
    contact_id bigint not null,
    type text,
    text text,
    due_date timestamp with time zone,
    done_date timestamp with time zone,
    sales_id bigint
);

create table public.configuration (
    id integer not null default 1 primary key,
    config jsonb not null default '{}'::jsonb,
    constraint configuration_singleton check (id = 1)
);

create table public.favicons_excluded_domains (
    id bigint generated by default as identity primary key,
    domain text not null
);

--
-- Foreign keys
--

alter table public.companies
    add constraint companies_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.contacts
    add constraint contacts_company_id_fkey foreign key (company_id) references public.companies(id) on update cascade on delete cascade;

alter table public.contacts
    add constraint contacts_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.contact_notes
    add constraint "contactNotes_contact_id_fkey" foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;

alter table public.contact_notes
    add constraint "contactNotes_sales_id_fkey" foreign key (sales_id) references public.sales(id) on update cascade on delete cascade;

alter table public.deals
    add constraint deals_company_id_fkey foreign key (company_id) references public.companies(id) on update cascade on delete cascade;

alter table public.deals
    add constraint deals_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.deal_notes
    add constraint "dealNotes_deal_id_fkey" foreign key (deal_id) references public.deals(id) on update cascade on delete cascade;

alter table public.deal_notes
    add constraint "dealNotes_sales_id_fkey" foreign key (sales_id) references public.sales(id);

alter table public.sales
    add constraint sales_user_id_fkey foreign key (user_id) references auth.users(id);

alter table public.tasks
    add constraint tasks_contact_id_fkey foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;

-- Legacy primary key constraint names (from before snake_case rename)
alter table only public.contact_notes
    add constraint "contactNotes_pkey" primary key (id);

alter table only public.deal_notes
    add constraint "dealNotes_pkey" primary key (id);

--
-- Indexes on foreign keys
--

create index contact_notes_contact_id_idx on public.contact_notes using btree (contact_id);
create index contacts_company_id_idx on public.contacts using btree (company_id);
create index deal_notes_deal_id_idx on public.deal_notes using btree (deal_id);
create index deals_company_id_idx on public.deals using btree (company_id);

--
-- CARE claims intelligence
-- Tracks carriers, their adjusters, claims, estimates, and persisted policy
-- analyses so the firm can study how claims resolve over time.
--

create table public.carriers (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    name text not null,
    naic_code text,
    notes text,
    sales_id bigint
);

create table public.carrier_adjusters (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    carrier_id bigint,
    first_name text,
    last_name text,
    license_number text,
    license_state text,
    email text,
    phone text,
    notes text,
    sales_id bigint
);

create table public.claims (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    claim_number text,
    carrier_id bigint,
    carrier_adjuster_id bigint,
    deal_id bigint,
    contact_id bigint,
    policy_number text,
    loss_state text,
    date_of_loss date,
    peril text,
    status text not null default 'open',
    resolution_method text,
    resolved_at date,
    settlement_amount numeric(14, 2),
    attorney_involved boolean not null default false,
    mediation_representative text,
    notes text,
    sales_id bigint,
    constraint claims_status_check
        check (status in ('open', 'in_progress', 'resolved', 'closed')),
    constraint claims_resolution_method_check
        check (resolution_method is null or resolution_method in
            ('negotiation', 'appraisal', 'appraisal_award', 'mediation',
             'litigation', 'denied', 'withdrawn')),
    constraint claims_mediation_representative_check
        check (mediation_representative is null or mediation_representative in
            ('public_adjuster', 'attorney', 'none'))
);

create table public.claim_estimates (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    claim_id bigint not null,
    source text not null,
    amount numeric(14, 2),
    estimate_date date,
    software text,
    notes text,
    sales_id bigint,
    constraint claim_estimates_source_check
        check (source in ('carrier', 'public_adjuster', 'independent'))
);

create table public.policy_analyses (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    claim_id bigint,
    carrier_id bigint,
    policy_state text,
    model text,
    analysis jsonb not null,
    sales_id bigint
);

alter table public.carriers
    add constraint carriers_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.carrier_adjusters
    add constraint carrier_adjusters_carrier_id_fkey foreign key (carrier_id) references public.carriers(id) on delete set null;
alter table public.carrier_adjusters
    add constraint carrier_adjusters_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.claims
    add constraint claims_carrier_id_fkey foreign key (carrier_id) references public.carriers(id) on delete set null;
alter table public.claims
    add constraint claims_carrier_adjuster_id_fkey foreign key (carrier_adjuster_id) references public.carrier_adjusters(id) on delete set null;
alter table public.claims
    add constraint claims_deal_id_fkey foreign key (deal_id) references public.deals(id) on delete set null;
alter table public.claims
    add constraint claims_contact_id_fkey foreign key (contact_id) references public.contacts(id) on delete set null;
alter table public.claims
    add constraint claims_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.claim_estimates
    add constraint claim_estimates_claim_id_fkey foreign key (claim_id) references public.claims(id) on update cascade on delete cascade;
alter table public.claim_estimates
    add constraint claim_estimates_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.policy_analyses
    add constraint policy_analyses_claim_id_fkey foreign key (claim_id) references public.claims(id) on delete set null;
alter table public.policy_analyses
    add constraint policy_analyses_carrier_id_fkey foreign key (carrier_id) references public.carriers(id) on delete set null;
alter table public.policy_analyses
    add constraint policy_analyses_sales_id_fkey foreign key (sales_id) references public.sales(id);

create index carrier_adjusters_carrier_id_idx on public.carrier_adjusters using btree (carrier_id);
create index claims_carrier_id_idx on public.claims using btree (carrier_id);
create index claims_carrier_adjuster_id_idx on public.claims using btree (carrier_adjuster_id);
create index claims_deal_id_idx on public.claims using btree (deal_id);
create index claims_contact_id_idx on public.claims using btree (contact_id);
create index claim_estimates_claim_id_idx on public.claim_estimates using btree (claim_id);
create index policy_analyses_claim_id_idx on public.policy_analyses using btree (claim_id);
create index policy_analyses_carrier_id_idx on public.policy_analyses using btree (carrier_id);
