--
-- Tables
-- This file declares all tables in the public schema.
--

-- Extensions
create extension if not exists "http" with schema "extensions";
create extension if not exists "citext" with schema "extensions";

-- Private schema (used by sales policies migration)
create schema if not exists "private";

create table public.companies (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    name text not null,
    sector text,
    size smallint,
    linkedin_url text,
    website extensions.citext,
    phone_number text,
    address text,
    zipcode text,
    city text,
    state_abbr text,
    sales_id bigint,
    context_links json,
    country text,
    description text,
    revenue text,
    tax_identifier text,
    logo jsonb
);

create table public.contacts (
    id bigint generated by default as identity primary key,
    first_name text,
    last_name text,
    gender text,
    title text,
    background text,
    avatar jsonb,
    first_seen timestamp with time zone,
    last_seen timestamp with time zone,
    has_newsletter boolean,
    status text,
    tags bigint[],
    company_id bigint,
    sales_id bigint,
    linkedin_url text,
    email_jsonb jsonb,
    phone_jsonb jsonb
);

create table public.contact_notes (
    id bigint generated by default as identity (sequence name public."contactNotes_id_seq") not null,
    contact_id bigint not null,
    text text,
    date timestamp with time zone default now(),
    sales_id bigint,
    status text,
    attachments jsonb[]
);

create table public.deals (
    id bigint generated by default as identity primary key,
    name text not null,
    company_id bigint,
    contact_ids bigint[],
    category text,
    stage text not null,
    description text,
    amount bigint,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    archived_at timestamp with time zone,
    expected_closing_date date,
    sales_id bigint,
    index smallint
);

create table public.deal_notes (
    id bigint generated by default as identity (sequence name public."dealNotes_id_seq") not null,
    deal_id bigint not null,
    type text,
    text text,
    date timestamp with time zone default now(),
    sales_id bigint,
    attachments jsonb[]
);

create table public.sales (
    id bigint generated by default as identity primary key,
    first_name text not null default 'Pending'::text,
    last_name text not null default 'Pending'::text,
    email extensions.citext not null,
    administrator boolean not null,
    user_id uuid not null,
    avatar jsonb,
    disabled boolean not null default false
);

create unique index uq__sales__user_id on public.sales using btree (user_id);

create table public.tags (
    id bigint generated by default as identity primary key,
    name text not null,
    color text not null
);

create table public.tasks (
    id bigint generated by default as identity primary key,
    contact_id bigint not null,
    type text,
    text text,
    due_date timestamp with time zone,
    done_date timestamp with time zone,
    sales_id bigint
);

create table public.configuration (
    id integer not null default 1 primary key,
    config jsonb not null default '{}'::jsonb,
    constraint configuration_singleton check (id = 1)
);

create table public.favicons_excluded_domains (
    id bigint generated by default as identity primary key,
    domain text not null
);

--
-- Foreign keys
--

alter table public.companies
    add constraint companies_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.contacts
    add constraint contacts_company_id_fkey foreign key (company_id) references public.companies(id) on update cascade on delete cascade;

alter table public.contacts
    add constraint contacts_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.contact_notes
    add constraint "contactNotes_contact_id_fkey" foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;

alter table public.contact_notes
    add constraint "contactNotes_sales_id_fkey" foreign key (sales_id) references public.sales(id) on update cascade on delete cascade;

alter table public.deals
    add constraint deals_company_id_fkey foreign key (company_id) references public.companies(id) on update cascade on delete cascade;

alter table public.deals
    add constraint deals_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.deal_notes
    add constraint "dealNotes_deal_id_fkey" foreign key (deal_id) references public.deals(id) on update cascade on delete cascade;

alter table public.deal_notes
    add constraint "dealNotes_sales_id_fkey" foreign key (sales_id) references public.sales(id);

alter table public.sales
    add constraint sales_user_id_fkey foreign key (user_id) references auth.users(id);

alter table public.tasks
    add constraint tasks_contact_id_fkey foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;

-- Legacy primary key constraint names (from before snake_case rename)
alter table only public.contact_notes
    add constraint "contactNotes_pkey" primary key (id);

alter table only public.deal_notes
    add constraint "dealNotes_pkey" primary key (id);

--
-- Indexes on foreign keys
--

create index contact_notes_contact_id_idx on public.contact_notes using btree (contact_id);
create index contacts_company_id_idx on public.contacts using btree (company_id);
create index deal_notes_deal_id_idx on public.deal_notes using btree (deal_id);
create index deals_company_id_idx on public.deals using btree (company_id);

--
-- Claims domain
-- Public-adjuster workflow: carriers, adjusters, policies, claims, estimates, settlements.
--

create table public.carriers (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    name text not null,
    naic_code text,
    claims_phone text,
    claims_email text,
    claims_fax text,
    claims_address text,
    website text,
    notes text
);

create table public.carrier_adjusters (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    carrier_id bigint references public.carriers(id) on delete set null,
    first_name text,
    last_name text,
    license_number text,
    license_state text,
    email text,
    phone text,
    role text,
    notes text
);

create table public.policies (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    contact_id bigint not null references public.contacts(id) on delete cascade,
    carrier_id bigint references public.carriers(id) on delete set null,
    policy_number text,
    policy_type text,
    effective_date date,
    expiration_date date,
    state_abbr text,
    premium_amount numeric,
    coverage_a_dwelling numeric,
    coverage_b_other_structures numeric,
    coverage_c_personal_property numeric,
    coverage_d_loss_of_use numeric,
    coverage_e_personal_liability numeric,
    coverage_f_medical_payments numeric,
    all_other_perils_deductible numeric,
    hurricane_deductible_pct numeric,
    hurricane_deductible_amount numeric,
    wind_hail_deductible_pct numeric,
    flood_deductible numeric,
    endorsements jsonb,
    exclusions jsonb,
    summary text,
    document_url text,
    raw_extracted jsonb,
    notes text,
    sales_id bigint references public.sales(id)
);

create table public.claims (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    contact_id bigint not null references public.contacts(id) on delete cascade,
    policy_id bigint references public.policies(id) on delete set null,
    carrier_id bigint references public.carriers(id) on delete set null,
    carrier_adjuster_id bigint references public.carrier_adjusters(id) on delete set null,
    deal_id bigint references public.deals(id) on delete set null,
    claim_number text,
    internal_claim_number text,
    date_of_loss date,
    date_reported date,
    type_of_loss text,
    cause_of_loss text,
    loss_location_address text,
    loss_location_city text,
    loss_location_state text,
    loss_location_zip text,
    status text not null default 'intake',
    description text,
    assigned_pa_sales_id bigint references public.sales(id),
    sales_id bigint references public.sales(id)
);

create table public.estimates (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    claim_id bigint not null references public.claims(id) on delete cascade,
    source text not null,
    source_name text,
    software text,
    estimate_date date,
    rcv_total numeric,
    acv_total numeric,
    depreciation_total numeric,
    deductible_applied numeric,
    net_payable numeric,
    overhead_pct numeric,
    profit_pct numeric,
    sales_tax numeric,
    document_url text,
    summary text,
    notes text,
    sales_id bigint references public.sales(id)
);

create table public.estimate_line_items (
    id bigint generated by default as identity primary key,
    estimate_id bigint not null references public.estimates(id) on delete cascade,
    room text,
    category text,
    code text,
    description text,
    quantity numeric,
    unit text,
    unit_price numeric,
    rcv numeric,
    acv numeric,
    depreciation numeric,
    age_life text,
    condition text,
    notes text
);

create table public.settlements (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    claim_id bigint not null unique references public.claims(id) on delete cascade,
    settled_at date,
    settlement_amount numeric,
    supplemental_amount numeric,
    depreciation_recoverable numeric,
    deductible_amount numeric,
    net_to_insured numeric,
    method text,
    pa_involved boolean default true,
    attorney_involved boolean default false,
    attorney_firm text,
    attorney_name text,
    mediator_appraiser_name text,
    mediator_appraiser_role text,
    days_to_settle integer,
    our_role text,
    notes text,
    sales_id bigint references public.sales(id)
);

create index policies_contact_id_idx on public.policies using btree (contact_id);
create index policies_carrier_id_idx on public.policies using btree (carrier_id);
create index policies_state_abbr_idx on public.policies using btree (state_abbr);
create index carrier_adjusters_carrier_id_idx on public.carrier_adjusters using btree (carrier_id);
create index claims_contact_id_idx on public.claims using btree (contact_id);
create index claims_policy_id_idx on public.claims using btree (policy_id);
create index claims_carrier_id_idx on public.claims using btree (carrier_id);
create index claims_status_idx on public.claims using btree (status);
create index claims_loss_state_idx on public.claims using btree (loss_location_state);
create index estimates_claim_id_idx on public.estimates using btree (claim_id);
create index estimate_line_items_estimate_id_idx on public.estimate_line_items using btree (estimate_id);
create index settlements_claim_id_idx on public.settlements using btree (claim_id);
create index settlements_method_idx on public.settlements using btree (method);

-- State-law compliance research module: a curated per-(state, topic)
-- knowledge base. status = draft|active|retired gates what surfaces to
-- claim staff; only the firm's compliance lead activates a row.
create table public.state_law_summaries (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    state_abbr text not null,
    topic text not null,
    title text not null,
    summary text not null,
    source_citation text,
    applies_to text[],
    last_reviewed_at date,
    reviewed_by_sales_id bigint references public.sales(id) on delete set null,
    status text not null default 'draft' check (status in ('draft','active','retired')),
    notes text,
    unique (state_abbr, topic)
);

create index state_law_summaries_state_idx on public.state_law_summaries using btree (state_abbr);
create index state_law_summaries_status_idx on public.state_law_summaries using btree (status);

-- Gmail integration: per-user OAuth + AI-triaged threads.
create table public.gmail_connections (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    sales_id bigint not null unique references public.sales(id) on delete cascade,
    google_email text not null,
    refresh_token text not null,
    scopes text[],
    last_synced_at timestamp with time zone,
    last_sync_status text check (last_sync_status in ('ok','error','running')),
    last_sync_error text
);

create index gmail_connections_sales_id_idx on public.gmail_connections using btree (sales_id);

create table public.email_triage (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    sales_id bigint not null references public.sales(id) on delete cascade,
    gmail_thread_id text not null,
    latest_message_id text,
    subject text,
    from_email text,
    from_name text,
    snippet text,
    body_excerpt text,
    received_at timestamp with time zone,
    claim_id bigint references public.claims(id) on delete set null,
    contact_id bigint references public.contacts(id) on delete set null,
    carrier_id bigint references public.carriers(id) on delete set null,
    carrier_adjuster_id bigint references public.carrier_adjusters(id) on delete set null,
    classification text check (classification in ('claim_correspondence','new_lead','admin','marketing','spam','unknown')),
    urgency text check (urgency in ('high','medium','low')),
    summary text,
    suggested_action text,
    ai_confidence numeric,
    ai_rationale text,
    status text not null default 'new' check (status in ('new','reviewed','archived','dismissed')),
    unique (sales_id, gmail_thread_id)
);

create index email_triage_sales_id_idx on public.email_triage using btree (sales_id);
create index email_triage_status_idx on public.email_triage using btree (status);
create index email_triage_claim_id_idx on public.email_triage using btree (claim_id);
create index email_triage_received_at_idx on public.email_triage using btree (received_at desc);

-- Phase 10: Google Calendar projection.
create table public.calendar_events (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    sales_id bigint not null references public.sales(id) on delete cascade,
    google_event_id text not null,
    google_calendar_id text not null default 'primary',
    ical_uid text,
    html_link text,
    summary text,
    description text,
    location text,
    starts_at timestamp with time zone,
    ends_at timestamp with time zone,
    all_day boolean default false,
    kind text check (kind in ('inspection','reinspection','appraisal','mediation','carrier_meeting','insured_meeting','deadline','other')),
    claim_id bigint references public.claims(id) on delete set null,
    contact_id bigint references public.contacts(id) on delete set null,
    carrier_adjuster_id bigint references public.carrier_adjusters(id) on delete set null,
    status text not null default 'scheduled' check (status in ('scheduled','completed','cancelled','no_show')),
    source text not null default 'created' check (source in ('created','synced')),
    ai_confidence numeric,
    ai_rationale text,
    notes text,
    unique (sales_id, google_event_id)
);

create index calendar_events_sales_id_idx on public.calendar_events using btree (sales_id);
create index calendar_events_claim_id_idx on public.calendar_events using btree (claim_id);
create index calendar_events_starts_at_idx on public.calendar_events using btree (starts_at);
create index calendar_events_status_idx on public.calendar_events using btree (status);

-- Phase 11: Dropbox integration.
create table public.dropbox_connections (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    sales_id bigint not null unique references public.sales(id) on delete cascade,
    dropbox_account_id text,
    dropbox_email text,
    access_token text,
    access_token_expires_at timestamp with time zone,
    refresh_token text not null,
    scopes text[]
);

create index dropbox_connections_sales_id_idx on public.dropbox_connections using btree (sales_id);

create table public.claim_dropbox_folders (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    claim_id bigint not null unique references public.claims(id) on delete cascade,
    folder_path text not null,
    configured_by_sales_id bigint references public.sales(id) on delete set null
);

create index claim_dropbox_folders_claim_id_idx on public.claim_dropbox_folders using btree (claim_id);

-- Phase 14: storm verification records.
create table public.claim_storm_verifications (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    claim_id bigint not null references public.claims(id) on delete cascade,
    sales_id bigint references public.sales(id) on delete set null,
    source text not null check (source in ('hailtrace','corelogic','verisk_pcs','noaa_spc','manual','other')),
    event_date date,
    event_type text check (event_type in ('hail','wind','tornado','hurricane','flood','lightning','other')),
    hail_size_inches numeric,
    wind_speed_mph numeric,
    wind_gust_mph numeric,
    distance_miles numeric,
    confidence text check (confidence in ('high','medium','low','unknown')),
    report_url text,
    report_pdf_path text,
    raw_response jsonb,
    notes text,
    matches_loss_date boolean,
    matches_loss_location boolean,
    unique (claim_id, source, event_date)
);

create index storm_verifications_claim_id_idx on public.claim_storm_verifications using btree (claim_id);
create index storm_verifications_event_date_idx on public.claim_storm_verifications using btree (event_date);

-- Phase 15: briefings history.
create table public.briefings (
    id bigint generated by default as identity primary key,
    generated_at timestamp with time zone not null default now(),
    sales_id bigint not null references public.sales(id) on delete cascade,
    content_markdown text not null,
    today_events_count integer default 0,
    urgent_emails_count integer default 0,
    stale_claims_count integer default 0,
    carriers_count integer default 0,
    gmail_draft_id text,
    model text
);

create index briefings_sales_id_idx on public.briefings using btree (sales_id);
create index briefings_generated_at_idx on public.briefings using btree (generated_at desc);
