--
-- Tables
-- This file declares all tables in the public schema.
--

-- Extensions
create extension if not exists "http" with schema "extensions";
create extension if not exists "citext" with schema "extensions";

-- Private schema (used by sales policies migration)
create schema if not exists "private";

create table public.companies (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    name text not null,
    sector text,
    size smallint,
    linkedin_url text,
    website extensions.citext,
    phone_number text,
    address text,
    zipcode text,
    city text,
    state_abbr text,
    sales_id bigint,
    context_links json,
    country text,
    description text,
    revenue text,
    tax_identifier text,
    logo jsonb
);

create table public.contacts (
    id bigint generated by default as identity primary key,
    first_name text,
    last_name text,
    gender text,
    title text,
    background text,
    avatar jsonb,
    first_seen timestamp with time zone,
    last_seen timestamp with time zone,
    has_newsletter boolean,
    status text,
    tags bigint[],
    company_id bigint,
    sales_id bigint,
    linkedin_url text,
    email_jsonb jsonb,
    phone_jsonb jsonb
);

create table public.contact_notes (
    id bigint generated by default as identity (sequence name public."contactNotes_id_seq") not null,
    contact_id bigint not null,
    text text,
    date timestamp with time zone default now(),
    sales_id bigint,
    status text,
    attachments jsonb[]
);

create table public.deals (
    id bigint generated by default as identity primary key,
    name text not null,
    company_id bigint,
    contact_ids bigint[],
    category text,
    stage text not null,
    description text,
    amount bigint,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    archived_at timestamp with time zone,
    expected_closing_date date,
    sales_id bigint,
    index smallint,
    claim_number text,
    date_of_loss date,
    loss_type text,
    loss_state text,
    loss_address text,
    loss_zipcode text,
    primary_carrier_id bigint
);

create table public.deal_notes (
    id bigint generated by default as identity (sequence name public."dealNotes_id_seq") not null,
    deal_id bigint not null,
    type text,
    text text,
    date timestamp with time zone default now(),
    sales_id bigint,
    attachments jsonb[]
);

create table public.sales (
    id bigint generated by default as identity primary key,
    first_name text not null default 'Pending'::text,
    last_name text not null default 'Pending'::text,
    email extensions.citext not null,
    administrator boolean not null,
    user_id uuid not null,
    avatar jsonb,
    disabled boolean not null default false,
    role text not null default 'adjuster'
);

create unique index uq__sales__user_id on public.sales using btree (user_id);

create table public.tags (
    id bigint generated by default as identity primary key,
    name text not null,
    color text not null
);

create table public.tasks (
    id bigint generated by default as identity primary key,
    contact_id bigint not null,
    type text,
    text text,
    due_date timestamp with time zone,
    done_date timestamp with time zone,
    sales_id bigint
);

create table public.configuration (
    id integer not null default 1 primary key,
    config jsonb not null default '{}'::jsonb,
    constraint configuration_singleton check (id = 1)
);

create table public.favicons_excluded_domains (
    id bigint generated by default as identity primary key,
    domain text not null
);

-- CARE multi-agent foundation tables (Roadmap Stage 1)

create table public.carriers (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    name text not null,
    naic_code text,
    phone text,
    email text,
    address text,
    claims_portal_url text,
    notes text,
    sales_id bigint
);

create table public.carrier_adjusters (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    carrier_id bigint,
    first_name text,
    last_name text,
    license_number text,
    license_state text,
    adjuster_type text,
    phone text,
    email text,
    notes text,
    sales_id bigint
);

create table public.policies (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    deal_id bigint not null,
    carrier_id bigint,
    policy_number text,
    named_insured text,
    policy_type text,
    effective_date date,
    expiration_date date,
    coverages jsonb not null default '{}'::jsonb,
    endorsements jsonb not null default '[]'::jsonb,
    exclusions jsonb not null default '[]'::jsonb,
    limits jsonb not null default '{}'::jsonb,
    deductibles jsonb not null default '{}'::jsonb,
    document_path text,
    sales_id bigint
);

create table public.document_templates (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    name text not null,
    description text,
    category text,
    file_path text,
    placeholders jsonb not null default '[]'::jsonb,
    sales_id bigint
);

create table public.task_templates (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    name text not null,
    description text,
    cadence text not null default 'per_claim_stage',
    trigger_stage text,
    active boolean not null default true,
    sales_id bigint
);

create table public.task_template_items (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    template_id bigint not null,
    title text not null,
    description text,
    assignee_role text,
    offset_days integer not null default 0,
    sort_order integer not null default 0
);

create table public.agent_runs (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    deal_id bigint,
    parent_run_id bigint,
    agent_type text not null,
    status text not null default 'queued',
    triggered_by bigint,
    input jsonb not null default '{}'::jsonb,
    error text,
    model text,
    tokens_input integer,
    tokens_output integer,
    started_at timestamp with time zone,
    finished_at timestamp with time zone
);

create table public.agent_outputs (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    run_id bigint,
    deal_id bigint,
    agent_type text not null,
    output_type text not null,
    title text,
    content text,
    data jsonb not null default '{}'::jsonb,
    status text not null default 'draft',
    reviewed_by bigint,
    sales_id bigint
);

--
-- Foreign keys
--

alter table public.companies
    add constraint companies_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.contacts
    add constraint contacts_company_id_fkey foreign key (company_id) references public.companies(id) on update cascade on delete cascade;

alter table public.contacts
    add constraint contacts_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.contact_notes
    add constraint "contactNotes_contact_id_fkey" foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;

alter table public.contact_notes
    add constraint "contactNotes_sales_id_fkey" foreign key (sales_id) references public.sales(id) on update cascade on delete cascade;

alter table public.deals
    add constraint deals_company_id_fkey foreign key (company_id) references public.companies(id) on update cascade on delete cascade;

alter table public.deals
    add constraint deals_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.deal_notes
    add constraint "dealNotes_deal_id_fkey" foreign key (deal_id) references public.deals(id) on update cascade on delete cascade;

alter table public.deal_notes
    add constraint "dealNotes_sales_id_fkey" foreign key (sales_id) references public.sales(id);

alter table public.sales
    add constraint sales_user_id_fkey foreign key (user_id) references auth.users(id);

alter table public.tasks
    add constraint tasks_contact_id_fkey foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;

-- CARE multi-agent foundation foreign keys

alter table public.deals
    add constraint deals_primary_carrier_id_fkey foreign key (primary_carrier_id) references public.carriers(id) on delete set null;

alter table public.carriers
    add constraint carriers_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.carrier_adjusters
    add constraint carrier_adjusters_carrier_id_fkey foreign key (carrier_id) references public.carriers(id) on update cascade on delete cascade;

alter table public.carrier_adjusters
    add constraint carrier_adjusters_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.policies
    add constraint policies_deal_id_fkey foreign key (deal_id) references public.deals(id) on update cascade on delete cascade;

alter table public.policies
    add constraint policies_carrier_id_fkey foreign key (carrier_id) references public.carriers(id) on delete set null;

alter table public.policies
    add constraint policies_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.document_templates
    add constraint document_templates_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.task_templates
    add constraint task_templates_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.task_template_items
    add constraint task_template_items_template_id_fkey foreign key (template_id) references public.task_templates(id) on update cascade on delete cascade;

alter table public.agent_runs
    add constraint agent_runs_deal_id_fkey foreign key (deal_id) references public.deals(id) on update cascade on delete cascade;

alter table public.agent_runs
    add constraint agent_runs_parent_run_id_fkey foreign key (parent_run_id) references public.agent_runs(id) on delete set null;

alter table public.agent_runs
    add constraint agent_runs_triggered_by_fkey foreign key (triggered_by) references public.sales(id);

alter table public.agent_outputs
    add constraint agent_outputs_run_id_fkey foreign key (run_id) references public.agent_runs(id) on delete set null;

alter table public.agent_outputs
    add constraint agent_outputs_deal_id_fkey foreign key (deal_id) references public.deals(id) on update cascade on delete cascade;

alter table public.agent_outputs
    add constraint agent_outputs_reviewed_by_fkey foreign key (reviewed_by) references public.sales(id);

alter table public.agent_outputs
    add constraint agent_outputs_sales_id_fkey foreign key (sales_id) references public.sales(id);

-- Legacy primary key constraint names (from before snake_case rename)
alter table only public.contact_notes
    add constraint "contactNotes_pkey" primary key (id);

alter table only public.deal_notes
    add constraint "dealNotes_pkey" primary key (id);

--
-- Indexes on foreign keys
--

create index contact_notes_contact_id_idx on public.contact_notes using btree (contact_id);
create index contacts_company_id_idx on public.contacts using btree (company_id);
create index deal_notes_deal_id_idx on public.deal_notes using btree (deal_id);
create index deals_company_id_idx on public.deals using btree (company_id);
create index deals_primary_carrier_id_idx on public.deals using btree (primary_carrier_id);
create index carrier_adjusters_carrier_id_idx on public.carrier_adjusters using btree (carrier_id);
create index policies_deal_id_idx on public.policies using btree (deal_id);
create index policies_carrier_id_idx on public.policies using btree (carrier_id);
create index task_template_items_template_id_idx on public.task_template_items using btree (template_id);
create index agent_runs_deal_id_idx on public.agent_runs using btree (deal_id);
create index agent_runs_parent_run_id_idx on public.agent_runs using btree (parent_run_id);
create index agent_outputs_run_id_idx on public.agent_outputs using btree (run_id);
create index agent_outputs_deal_id_idx on public.agent_outputs using btree (deal_id);
