#!/usr/bin/env python3
"""
CRM Pipeline Report - deterministic data pull for the Weekly Pipeline Review
directive (directives/weekly_pipeline_review.md).

Reads open deals and open tasks from CARE AI CRM (Supabase/PostgREST) and
writes a raw markdown snapshot to .tmp/pipeline_<date>.md. It does NO
analysis - judgment stays with the AI, per the DOE split.

Setup: copy .env.example to .env in second-brain/ and fill in
SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY.

Usage:
    python execution/crm_pipeline_report.py
    python execution/crm_pipeline_report.py --out somewhere/else.md

Uses only the Python standard library. Never invents data: if the API is
unreachable it exits non-zero with the error instead of writing a report.
"""

import argparse
import json
import os
import sys
import urllib.error
import urllib.parse
import urllib.request
from datetime import date, datetime, timezone
from pathlib import Path

BRAIN_ROOT = Path(__file__).resolve().parent.parent


def load_env() -> None:
    """Minimal .env loader so the script has no pip dependencies."""
    env_file = BRAIN_ROOT / ".env"
    if not env_file.exists():
        return
    for line in env_file.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        value = value.split("#", 1)[0].strip().strip("'\"")
        os.environ.setdefault(key.strip(), value)


def rest_get(base_url: str, key: str, table: str, params: dict) -> list:
    query = urllib.parse.urlencode(params)
    url = f"{base_url.rstrip('/')}/rest/v1/{table}?{query}"
    req = urllib.request.Request(
        url, headers={"apikey": key, "Authorization": f"Bearer {key}"}
    )
    with urllib.request.urlopen(req, timeout=30) as resp:
        return json.loads(resp.read().decode())


def fmt_amount(cents) -> str:
    if cents is None:
        return "-"
    return f"${cents:,.0f}"


def days_since(iso_ts: str) -> int:
    ts = datetime.fromisoformat(iso_ts.replace("Z", "+00:00"))
    return (datetime.now(timezone.utc) - ts).days


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", help="Output path (default .tmp/pipeline_<date>.md)")
    args = parser.parse_args()

    load_env()
    base_url = os.environ.get("SUPABASE_URL")
    key = os.environ.get("SUPABASE_SERVICE_ROLE_KEY")
    if not base_url or not key:
        print(
            "ERROR: SUPABASE_URL / SUPABASE_SERVICE_ROLE_KEY not set. "
            "Copy .env.example to .env and fill them in.",
            file=sys.stderr,
        )
        return 1

    today = date.today().isoformat()
    try:
        deals = rest_get(
            base_url, key, "deals",
            {"archived_at": "is.null", "order": "stage.asc,updated_at.desc",
             "select": "id,name,stage,amount,category,updated_at,expected_closing_date,company_id"},
        )
        companies = rest_get(base_url, key, "companies", {"select": "id,name"})
        open_tasks = rest_get(
            base_url, key, "tasks",
            {"done_date": "is.null", "order": "due_date.asc",
             "select": "id,text,type,due_date,contact_id"},
        )
    except (urllib.error.URLError, urllib.error.HTTPError, TimeoutError) as exc:
        print(f"ERROR: could not reach CRM API: {exc}", file=sys.stderr)
        return 1

    company_names = {c["id"]: c["name"] for c in companies}

    lines = [
        f"# Raw pipeline snapshot - {today}",
        "",
        "Generated by execution/crm_pipeline_report.py. Raw data only;",
        "analysis happens in the Weekly Pipeline Review directive.",
        "",
        f"## Open deals ({len(deals)})",
        "",
        "| Deal | Company | Stage | Amount | Expected close | Days since update |",
        "|------|---------|-------|--------|----------------|-------------------|",
    ]
    for d in deals:
        lines.append(
            "| {name} | {company} | {stage} | {amount} | {close} | {stale} |".format(
                name=d["name"],
                company=company_names.get(d.get("company_id"), "-"),
                stage=d["stage"],
                amount=fmt_amount(d.get("amount")),
                close=d.get("expected_closing_date") or "-",
                stale=days_since(d["updated_at"]),
            )
        )

    lines += ["", f"## Open tasks ({len(open_tasks)})", ""]
    if open_tasks:
        lines += ["| Task | Type | Due | Overdue? |", "|------|------|-----|----------|"]
        for t in open_tasks:
            due = (t.get("due_date") or "")[:10]
            overdue = "YES" if due and due < today else ""
            lines.append(f"| {t['text']} | {t.get('type') or '-'} | {due or '-'} | {overdue} |")
    else:
        lines.append("(none)")
    lines.append("")

    out_path = Path(args.out) if args.out else BRAIN_ROOT / ".tmp" / f"pipeline_{today}.md"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines))
    print(f"Wrote {out_path} ({len(deals)} deals, {len(open_tasks)} open tasks)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
