-- Phase 11: Dropbox integration.
-- Per-user OAuth (separate from Google) + per-claim folder linkage.
-- Files themselves are NOT cached in the CRM — listing is live against
-- the Dropbox API. Caching is a future optimization.

create table public.dropbox_connections (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    sales_id bigint not null unique references public.sales(id) on delete cascade,
    dropbox_account_id text,
    dropbox_email text,
    access_token text,
    access_token_expires_at timestamp with time zone,
    refresh_token text not null,
    scopes text[]
);

create index dropbox_connections_sales_id_idx on public.dropbox_connections using btree (sales_id);

alter table public.dropbox_connections enable row level security;

create policy "Dropbox connections: owner read"
    on public.dropbox_connections for select to authenticated
    using (sales_id in (select id from public.sales where user_id = auth.uid()));
create policy "Dropbox connections: owner insert"
    on public.dropbox_connections for insert to authenticated
    with check (sales_id in (select id from public.sales where user_id = auth.uid()));
create policy "Dropbox connections: owner update"
    on public.dropbox_connections for update to authenticated
    using (sales_id in (select id from public.sales where user_id = auth.uid()))
    with check (sales_id in (select id from public.sales where user_id = auth.uid()));
create policy "Dropbox connections: owner delete"
    on public.dropbox_connections for delete to authenticated
    using (sales_id in (select id from public.sales where user_id = auth.uid()));

-- Linkage: which Dropbox folder holds this claim's files. ONE folder
-- per claim. The folder is shared across the firm — anyone can see
-- the linkage, only the configurer can change it.
create table public.claim_dropbox_folders (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    claim_id bigint not null unique references public.claims(id) on delete cascade,
    folder_path text not null,
    configured_by_sales_id bigint references public.sales(id) on delete set null
);

create index claim_dropbox_folders_claim_id_idx on public.claim_dropbox_folders using btree (claim_id);

alter table public.claim_dropbox_folders enable row level security;
create policy "Claim dropbox folders: authenticated read"
    on public.claim_dropbox_folders for select to authenticated using (true);
create policy "Claim dropbox folders: authenticated write"
    on public.claim_dropbox_folders for all to authenticated
    using (true) with check (true);
