-- Estimates (Roadmap Stage 9 - Estimate Comparison agent)
-- Stores the estimates entered on a claim (the carrier's estimate and the
-- public adjuster's / contractor's estimate) so the Estimate Comparison agent
-- can compare them and draft a negotiation letter.

create table public.estimates (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    deal_id bigint not null,
    source text not null default 'carrier',
    label text,
    total_rcv numeric,
    total_acv numeric,
    depreciation numeric,
    deductible numeric,
    content text,
    sales_id bigint
);

alter table public.estimates
    add constraint estimates_deal_id_fkey foreign key (deal_id) references public.deals(id) on update cascade on delete cascade;
alter table public.estimates
    add constraint estimates_sales_id_fkey foreign key (sales_id) references public.sales(id);

create index estimates_deal_id_idx on public.estimates using btree (deal_id);

create or replace trigger set_estimates_sales_id_trigger
    before insert on public.estimates
    for each row execute function public.set_sales_id_default();

alter table public.estimates enable row level security;
create policy "Enable all access for authenticated users" on public.estimates to authenticated using (true) with check (true);

grant all on table public.estimates to anon, authenticated, service_role;
grant all on sequence public.estimates_id_seq to anon, authenticated, service_role;
