-- Phase 15a: briefing history.
-- Persist every generated daily briefing so staff can scroll back and
-- supervisors can see what the team has been getting.

create table public.briefings (
    id bigint generated by default as identity primary key,
    generated_at timestamp with time zone not null default now(),
    sales_id bigint not null references public.sales(id) on delete cascade,
    content_markdown text not null,
    today_events_count integer default 0,
    urgent_emails_count integer default 0,
    stale_claims_count integer default 0,
    carriers_count integer default 0,
    gmail_draft_id text,
    model text
);

create index briefings_sales_id_idx on public.briefings using btree (sales_id);
create index briefings_generated_at_idx on public.briefings using btree (generated_at desc);

alter table public.briefings enable row level security;

-- Any staff member can read briefings (supervisor view); only the
-- briefing's owner can mutate their own.
create policy "Briefings: authenticated read"
    on public.briefings for select to authenticated using (true);
create policy "Briefings: owner insert"
    on public.briefings for insert to authenticated
    with check (sales_id in (select id from public.sales where user_id = auth.uid()));
create policy "Briefings: owner update"
    on public.briefings for update to authenticated
    using (sales_id in (select id from public.sales where user_id = auth.uid()))
    with check (sales_id in (select id from public.sales where user_id = auth.uid()));
create policy "Briefings: owner delete"
    on public.briefings for delete to authenticated
    using (sales_id in (select id from public.sales where user_id = auth.uid()));
