-- Security hardening (Roadmap Stage 12 - Security agent)
-- An immutable audit log of sensitive (financial) actions: who, what, when.
-- Rows are written only by the security-definer trigger function; the log is
-- readable by finance roles and administrators.

create table public.audit_log (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    table_name text not null,
    record_id bigint,
    action text not null,
    actor_sales_id bigint
);

alter table public.audit_log
    add constraint audit_log_actor_sales_id_fkey foreign key (actor_sales_id) references public.sales(id);

create index audit_log_created_at_idx on public.audit_log using btree (created_at);

CREATE OR REPLACE FUNCTION "public"."record_audit"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
  actor bigint;
begin
  select id into actor from public.sales where user_id = auth.uid();
  if (tg_op = 'DELETE') then
    insert into public.audit_log (table_name, record_id, action, actor_sales_id)
    values (tg_table_name, old.id, tg_op, actor);
    return old;
  else
    insert into public.audit_log (table_name, record_id, action, actor_sales_id)
    values (tg_table_name, new.id, tg_op, actor);
    return new;
  end if;
end;
$$;

create or replace trigger audit_financial_ledger
    after insert or update or delete on public.financial_ledger
    for each row execute function public.record_audit();

create or replace trigger audit_settlements
    after insert or update or delete on public.settlements
    for each row execute function public.record_audit();

-- Only finance roles / administrators may read the audit log. There is no
-- insert policy: rows are written solely by the trigger function above.
alter table public.audit_log enable row level security;
create policy "Audit read for finance roles" on public.audit_log
    for select to authenticated
    using (exists (select 1 from public.sales s where s.user_id = auth.uid() and (s.administrator or s.role in ('owner', 'accounting'))));

grant all on function public.record_audit() to anon, authenticated, service_role;
grant all on table public.audit_log to anon, authenticated, service_role;
grant all on sequence public.audit_log_id_seq to anon, authenticated, service_role;
