-- State compliance reference (Roadmap Stage 5 - State Compliance agent)
-- A per-state reference of public-adjusting rules the firm maintains. The
-- State Compliance agent reads the row for a claim's loss state.

create table public.state_compliance_rules (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    state_abbr text not null,
    state_name text not null,
    pa_license_required boolean,
    fee_rules text,
    contract_rules text,
    claim_deadlines text,
    required_disclosures text,
    statute_of_limitations text,
    dispute_options text,
    notes text,
    sales_id bigint
);

create unique index state_compliance_rules_state_abbr_idx
    on public.state_compliance_rules using btree (state_abbr);

alter table public.state_compliance_rules
    add constraint state_compliance_rules_sales_id_fkey foreign key (sales_id) references public.sales(id);

create or replace trigger set_state_compliance_rules_sales_id_trigger
    before insert on public.state_compliance_rules
    for each row execute function public.set_sales_id_default();

alter table public.state_compliance_rules enable row level security;
create policy "Enable all access for authenticated users" on public.state_compliance_rules to authenticated using (true) with check (true);

grant all on table public.state_compliance_rules to anon, authenticated, service_role;
grant all on sequence public.state_compliance_rules_id_seq to anon, authenticated, service_role;

-- Seed one row per US state + DC so the firm has a complete worklist.
-- Rule fields are intentionally left blank for the firm to fill in with
-- verified, current information.
insert into public.state_compliance_rules (state_abbr, state_name) values
    ('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'),
    ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'),
    ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'),
    ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'),
    ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'),
    ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'),
    ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'),
    ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'),
    ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'),
    ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'),
    ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'),
    ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'),
    ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'),
    ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'),
    ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'),
    ('WI', 'Wisconsin'), ('WY', 'Wyoming')
on conflict (state_abbr) do nothing;
