-- State-law compliance research module: a curated knowledge base of
-- per-(state, topic) summaries the firm's compliance lead maintains.
-- Source of truth lives in supabase/schemas/. Hand-written migration.
--
-- Critical design constraint: this AI assistant must NEVER invent
-- statute numbers or treat its outputs as authoritative legal answers.
-- The schema enforces the workflow:
--   - status = 'draft'   → research checklist; not shown to claim staff
--                          unless they explicitly opt in to "show drafts"
--   - status = 'active'  → reviewed and approved by a named sales (PA)
--                          user; safe to surface as guidance with a
--                          standing "verify before relying" disclaimer
--   - status = 'retired' → kept for audit; never surfaced

create table public.state_law_summaries (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    state_abbr text not null,
    topic text not null,
    title text not null,
    summary text not null,
    source_citation text,
    applies_to text[],
    last_reviewed_at date,
    reviewed_by_sales_id bigint references public.sales(id) on delete set null,
    status text not null default 'draft' check (status in ('draft','active','retired')),
    notes text,
    unique (state_abbr, topic)
);

create index state_law_summaries_state_idx on public.state_law_summaries using btree (state_abbr);
create index state_law_summaries_status_idx on public.state_law_summaries using btree (status);

-- updated_at is maintained by the application on each write (no
-- trigger function exists in this codebase to share, and adding one
-- here for one table isn't worth it).

alter table public.state_law_summaries enable row level security;

create policy "State law summaries full access"
    on public.state_law_summaries for all to authenticated
    using (true) with check (true);

-- Seed: Florida research checklists. Every row is `draft` and has no
-- source_citation — the firm's compliance lead must fill in current
-- statute references and flip status to 'active'. The summary text is
-- a CHECKLIST of what to verify, not a legal answer.

insert into public.state_law_summaries (state_abbr, topic, title, summary, status, notes) values
('FL', 'pa_licensing',
 'Public-adjuster licensing — Florida',
 E'CHECKLIST (DRAFT — compliance lead to verify and replace):\n- Confirm FL public-adjuster license is current for every PA on this claim. License lookup: MyFloridaCFO.com.\n- Confirm appointment with employing PA firm is current.\n- Confirm continuing-education hours are on file for the current renewal cycle.\n- Verify that any apprentice PA on the file is operating under a licensed PA''s supervision per FL apprenticeship rules.\n- Confirm the firm''s surety bond is on file and current.',
 'draft', 'Seeded by AI. Compliance lead must add citations and flip to active before staff rely on this.'),

('FL', 'pa_fee_caps',
 'PA fee caps — Florida',
 E'CHECKLIST (DRAFT — verify current law before quoting any fee):\n- Florida caps PA fees by statute, and the cap CHANGED in recent reform cycles (2021 SB 76 and 2022 SB 2A in particular tightened caps for declared-emergency claims). Look up the CURRENT cap before signing any contract.\n- Two distinct rates typically apply: standard claims vs. claims arising from a declared state of emergency (hurricane / named storm). Confirm which applies for the date of loss on this file.\n- Confirm the contract states the fee percentage in the format required by current FL rule.\n- Confirm the fee is calculated on the correct base (paid amount, not estimate amount).\n- Reopened / supplemental claims may have a separate cap rule — verify.',
 'draft', 'Seeded by AI. FL fee-cap law changed multiple times 2021-2023; cite current statute before activating.'),

('FL', 'pa_contract_requirements',
 'PA contract requirements — Florida',
 E'CHECKLIST (DRAFT — verify each requirement against current FL rule):\n- Standard contract language and font-size requirements mandated by FL rule.\n- Right-to-cancel / cooling-off period disclosure.\n- Required identification of insured, property, and date of loss.\n- Signature of insured AND any co-insured / mortgagee where required.\n- Required notice of the consumer''s right to file complaints with the FL Dept of Financial Services.\n- For hurricane / named-storm claims arising during a declared state of emergency, additional contract restrictions may apply — confirm.',
 'draft', 'Seeded by AI. Compare against current DFS-prescribed contract form before activating.'),

('FL', 'pa_solicitation_rules',
 'Solicitation rules — Florida',
 E'CHECKLIST (DRAFT — verify current FL rule):\n- Confirm any post-loss waiting period between event and first solicitation contact (FL has imposed waiting periods after declared emergencies in recent reforms).\n- No solicitation at the property between certain hours (verify current window).\n- No solicitation while a carrier representative or law-enforcement officer is on premises performing official duties.\n- No misrepresentation of affiliation with any government, carrier, or contractor.\n- Confirm the firm''s solicitation script and door-knock practice complies.',
 'draft', 'Seeded by AI. Time-of-day and waiting-period rules have shifted; verify before activating.'),

('FL', 'statute_of_limitations',
 'Statute of limitations & claim notice — Florida',
 E'CHECKLIST (DRAFT — verify current FL deadlines for this claim):\n- Initial notice of claim: FL reform cycles have SHORTENED windows. Confirm current days-from-loss to notify the carrier.\n- Supplemental / reopened claim deadline (separate from initial notice).\n- Suit filing deadline (general breach-of-contract vs. specific 627 chapter rules).\n- Whether the claim''s date of loss falls under the OLD rule or the NEW rule based on FL reform effective dates.\n- Document the dates of every required notice in the CRM for the file.',
 'draft', 'Seeded by AI. FL notice deadlines were shortened twice 2021-2022. Cite the exact statute for the DOL on this claim.'),

('FL', 'appraisal_clause',
 'Appraisal clause enforcement — Florida',
 E'CHECKLIST (DRAFT — verify):\n- Confirm the policy form contains an appraisal clause. Read the exact language: invocation, scope (amount of loss vs. coverage), appraiser selection, umpire selection, who pays what.\n- Confirm FL''s current rule on enforceability of appraisal (statutory and case-law).\n- Confirm whether unresolved coverage disputes can be carved out of appraisal or must be litigated first.\n- Confirm the PA''s role in appraisal under FL practice — can a PA serve as appraiser, or must it be an independent third party? Verify before agreeing to serve.\n- Document the appraisal invocation in writing with proof of delivery.',
 'draft', 'Seeded by AI. FL appraisal case-law is active; verify current state before invoking.'),

('FL', 'mediation_program',
 'State-administered mediation — Florida',
 E'CHECKLIST (DRAFT — verify current DFS mediation program):\n- Confirm eligibility (claim type, amount in dispute thresholds).\n- Who pays the mediator fee under current rule.\n- Confirm whether a licensed PA can represent the insured at the mediation, or whether an attorney is required.\n- Confirm what time-bars / waivers attach to mediation outcomes.\n- Document mediator name and role per claim for pattern analysis.',
 'draft', 'Seeded by AI. DFS mediation program details have shifted; verify before requesting.'),

('FL', 'bad_faith_standard',
 'Bad-faith claims standard — Florida',
 E'CHECKLIST (DRAFT — verify):\n- Confirm current FL bad-faith standard (statutory under Ch. 624 and case-law overlay).\n- Confirm the prerequisite Civil Remedy Notice (CRN) process: required content, where filed, cure period before suit.\n- Recent reforms changed the attorney-fee landscape for bad-faith suits — confirm whether and how that affects the firm''s recommendation to hand off to counsel.\n- Document every carrier delay, denial, and undervaluation event with date and evidence; this is the substrate for any future bad-faith claim.\n- DO NOT advise the insured on bad-faith strategy yourself; route to vetted counsel.',
 'draft', 'Seeded by AI. Bad-faith landscape changed materially with 2022-2023 reforms; cite current statute.'),

('FL', 'matching_law',
 'Matching of damaged with undamaged materials — Florida',
 E'CHECKLIST (DRAFT — verify):\n- Confirm current FL rule on matching of roof / siding / interior finishes (statutory and case-law).\n- Confirm whether the rule applies to the policy form on file (some forms exclude or modify the matching obligation).\n- Document carrier''s position in writing if they refuse to match — needed for supplement / appraisal / suit.\n- Check whether the policy''s ordinance-and-law coverage tier interacts with matching for code-driven replacements.',
 'draft', 'Seeded by AI. Matching law in FL has been actively litigated; verify current state.'),

('FL', 'anti_concurrent_causation',
 'Anti-concurrent-causation clauses — Florida',
 E'CHECKLIST (DRAFT — verify):\n- Read the EXACT ACC language in the policy form on this claim. ACC clauses are NOT all the same.\n- Confirm whether the carrier is using ACC to deny on a peril-mixing argument (e.g., wind + water).\n- Confirm FL''s current judicial treatment of the specific ACC language in the policy.\n- If the loss involves a covered peril that occurred FIRST and an excluded peril followed, the analysis differs from simultaneous-peril losses — be precise about timeline.',
 'draft', 'Seeded by AI. ACC enforceability is fact-specific; cite the policy language verbatim.');
