-- Claims domain: carriers, carrier_adjusters, policies, claims, estimates,
-- estimate_line_items, settlements + claims_summary view + RLS.
-- Source of truth lives in supabase/schemas/. This migration is hand-written
-- (rather than via `supabase db diff`) because the schema additions are
-- self-contained and additive.

create table public.carriers (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    name text not null,
    naic_code text,
    claims_phone text,
    claims_email text,
    claims_fax text,
    claims_address text,
    website text,
    notes text
);

create table public.carrier_adjusters (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    carrier_id bigint references public.carriers(id) on delete set null,
    first_name text,
    last_name text,
    license_number text,
    license_state text,
    email text,
    phone text,
    role text,
    notes text
);

create table public.policies (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    contact_id bigint not null references public.contacts(id) on delete cascade,
    carrier_id bigint references public.carriers(id) on delete set null,
    policy_number text,
    policy_type text,
    effective_date date,
    expiration_date date,
    state_abbr text,
    premium_amount numeric,
    coverage_a_dwelling numeric,
    coverage_b_other_structures numeric,
    coverage_c_personal_property numeric,
    coverage_d_loss_of_use numeric,
    coverage_e_personal_liability numeric,
    coverage_f_medical_payments numeric,
    all_other_perils_deductible numeric,
    hurricane_deductible_pct numeric,
    hurricane_deductible_amount numeric,
    wind_hail_deductible_pct numeric,
    flood_deductible numeric,
    endorsements jsonb,
    exclusions jsonb,
    summary text,
    document_url text,
    raw_extracted jsonb,
    notes text,
    sales_id bigint references public.sales(id)
);

create table public.claims (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    contact_id bigint not null references public.contacts(id) on delete cascade,
    policy_id bigint references public.policies(id) on delete set null,
    carrier_id bigint references public.carriers(id) on delete set null,
    carrier_adjuster_id bigint references public.carrier_adjusters(id) on delete set null,
    deal_id bigint references public.deals(id) on delete set null,
    claim_number text,
    internal_claim_number text,
    date_of_loss date,
    date_reported date,
    type_of_loss text,
    cause_of_loss text,
    loss_location_address text,
    loss_location_city text,
    loss_location_state text,
    loss_location_zip text,
    status text not null default 'intake',
    description text,
    assigned_pa_sales_id bigint references public.sales(id),
    sales_id bigint references public.sales(id)
);

create table public.estimates (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    claim_id bigint not null references public.claims(id) on delete cascade,
    source text not null,
    source_name text,
    software text,
    estimate_date date,
    rcv_total numeric,
    acv_total numeric,
    depreciation_total numeric,
    deductible_applied numeric,
    net_payable numeric,
    overhead_pct numeric,
    profit_pct numeric,
    sales_tax numeric,
    document_url text,
    summary text,
    notes text,
    sales_id bigint references public.sales(id)
);

create table public.estimate_line_items (
    id bigint generated by default as identity primary key,
    estimate_id bigint not null references public.estimates(id) on delete cascade,
    room text,
    category text,
    code text,
    description text,
    quantity numeric,
    unit text,
    unit_price numeric,
    rcv numeric,
    acv numeric,
    depreciation numeric,
    age_life text,
    condition text,
    notes text
);

create table public.settlements (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    claim_id bigint not null unique references public.claims(id) on delete cascade,
    settled_at date,
    settlement_amount numeric,
    supplemental_amount numeric,
    depreciation_recoverable numeric,
    deductible_amount numeric,
    net_to_insured numeric,
    method text,
    pa_involved boolean default true,
    attorney_involved boolean default false,
    attorney_firm text,
    attorney_name text,
    mediator_appraiser_name text,
    mediator_appraiser_role text,
    days_to_settle integer,
    our_role text,
    notes text,
    sales_id bigint references public.sales(id)
);

create index policies_contact_id_idx on public.policies using btree (contact_id);
create index policies_carrier_id_idx on public.policies using btree (carrier_id);
create index policies_state_abbr_idx on public.policies using btree (state_abbr);
create index carrier_adjusters_carrier_id_idx on public.carrier_adjusters using btree (carrier_id);
create index claims_contact_id_idx on public.claims using btree (contact_id);
create index claims_policy_id_idx on public.claims using btree (policy_id);
create index claims_carrier_id_idx on public.claims using btree (carrier_id);
create index claims_status_idx on public.claims using btree (status);
create index claims_loss_state_idx on public.claims using btree (loss_location_state);
create index estimates_claim_id_idx on public.estimates using btree (claim_id);
create index estimate_line_items_estimate_id_idx on public.estimate_line_items using btree (estimate_id);
create index settlements_claim_id_idx on public.settlements using btree (claim_id);
create index settlements_method_idx on public.settlements using btree (method);

create or replace view public.claims_summary with (security_invoker = on) as
select
    cl.id,
    cl.created_at,
    cl.updated_at,
    cl.contact_id,
    cl.policy_id,
    cl.carrier_id,
    cl.carrier_adjuster_id,
    cl.deal_id,
    cl.claim_number,
    cl.internal_claim_number,
    cl.date_of_loss,
    cl.date_reported,
    cl.type_of_loss,
    cl.cause_of_loss,
    cl.loss_location_address,
    cl.loss_location_city,
    cl.loss_location_state,
    cl.loss_location_zip,
    cl.status,
    cl.description,
    cl.assigned_pa_sales_id,
    cl.sales_id,
    co.first_name as insured_first_name,
    co.last_name as insured_last_name,
    car.name as carrier_name,
    car.naic_code as carrier_naic,
    (ca.first_name || ' ' || ca.last_name) as carrier_adjuster_name,
    ca.license_number as carrier_adjuster_license,
    p.policy_number,
    p.policy_type,
    s.settlement_amount,
    s.method as settlement_method,
    s.settled_at,
    s.days_to_settle,
    count(distinct e.id) as nb_estimates
from public.claims cl
    left join public.contacts co on co.id = cl.contact_id
    left join public.carriers car on car.id = cl.carrier_id
    left join public.carrier_adjusters ca on ca.id = cl.carrier_adjuster_id
    left join public.policies p on p.id = cl.policy_id
    left join public.settlements s on s.claim_id = cl.id
    left join public.estimates e on e.claim_id = cl.id
group by cl.id, co.first_name, co.last_name, car.name, car.naic_code,
         ca.first_name, ca.last_name, ca.license_number,
         p.policy_number, p.policy_type,
         s.settlement_amount, s.method, s.settled_at, s.days_to_settle;

alter table public.carriers enable row level security;
alter table public.carrier_adjusters enable row level security;
alter table public.policies enable row level security;
alter table public.claims enable row level security;
alter table public.estimates enable row level security;
alter table public.estimate_line_items enable row level security;
alter table public.settlements enable row level security;

create policy "Carriers full access" on public.carriers for all to authenticated using (true) with check (true);
create policy "Carrier adjusters full access" on public.carrier_adjusters for all to authenticated using (true) with check (true);
create policy "Policies full access" on public.policies for all to authenticated using (true) with check (true);
create policy "Claims full access" on public.claims for all to authenticated using (true) with check (true);
create policy "Estimates full access" on public.estimates for all to authenticated using (true) with check (true);
create policy "Estimate line items full access" on public.estimate_line_items for all to authenticated using (true) with check (true);
create policy "Settlements full access" on public.settlements for all to authenticated using (true) with check (true);
