-- Gmail integration: per-user OAuth connections + AI-triaged email threads.
-- Hand-written migration (additive, claim-domain extension). Declarative
-- mirror lives in supabase/schemas/.

-- One Gmail account per CRM user (sales). refresh_token is the only
-- long-lived secret we store and it's protected by RLS so only the
-- owning user can read their own row through a user-scoped client. The
-- gmail-triage edge function uses the service-role client to read it.
create table public.gmail_connections (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    sales_id bigint not null unique references public.sales(id) on delete cascade,
    google_email text not null,
    refresh_token text not null,
    scopes text[],
    last_synced_at timestamp with time zone,
    last_sync_status text check (last_sync_status in ('ok','error','running')),
    last_sync_error text
);

create index gmail_connections_sales_id_idx on public.gmail_connections using btree (sales_id);

alter table public.gmail_connections enable row level security;

-- Only the owning sales user can see / edit their own connection.
create policy "Gmail connections: owner read"
    on public.gmail_connections for select to authenticated
    using (sales_id in (select id from public.sales where user_id = auth.uid()));
create policy "Gmail connections: owner insert"
    on public.gmail_connections for insert to authenticated
    with check (sales_id in (select id from public.sales where user_id = auth.uid()));
create policy "Gmail connections: owner update"
    on public.gmail_connections for update to authenticated
    using (sales_id in (select id from public.sales where user_id = auth.uid()))
    with check (sales_id in (select id from public.sales where user_id = auth.uid()));
create policy "Gmail connections: owner delete"
    on public.gmail_connections for delete to authenticated
    using (sales_id in (select id from public.sales where user_id = auth.uid()));

-- One row per Gmail thread we've classified. We intentionally don't
-- store the full message body in the CRM — only what the model needs
-- to surface in the triage UI (subject, sender, snippet, body_excerpt
-- = first ~4 KB of body). The user opens the full thread in Gmail.
create table public.email_triage (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    sales_id bigint not null references public.sales(id) on delete cascade,
    gmail_thread_id text not null,
    latest_message_id text,
    subject text,
    from_email text,
    from_name text,
    snippet text,
    body_excerpt text,
    received_at timestamp with time zone,

    -- AI-detected links to CRM records. Nullable; staff can correct.
    claim_id bigint references public.claims(id) on delete set null,
    contact_id bigint references public.contacts(id) on delete set null,
    carrier_id bigint references public.carriers(id) on delete set null,
    carrier_adjuster_id bigint references public.carrier_adjusters(id) on delete set null,

    classification text check (classification in ('claim_correspondence','new_lead','admin','marketing','spam','unknown')),
    urgency text check (urgency in ('high','medium','low')),
    summary text,
    suggested_action text,
    ai_confidence numeric,
    ai_rationale text,

    status text not null default 'new' check (status in ('new','reviewed','archived','dismissed')),

    unique (sales_id, gmail_thread_id)
);

create index email_triage_sales_id_idx on public.email_triage using btree (sales_id);
create index email_triage_status_idx on public.email_triage using btree (status);
create index email_triage_claim_id_idx on public.email_triage using btree (claim_id);
create index email_triage_received_at_idx on public.email_triage using btree (received_at desc);

alter table public.email_triage enable row level security;

-- Email triage is firm-internal but tied to the user who owns the Gmail
-- connection. Other staff can READ their colleagues' triaged email
-- (so a supervisor can re-assign or backfill links), but only the
-- owning sales user can edit or delete their own rows.
create policy "Email triage: authenticated read"
    on public.email_triage for select to authenticated using (true);
create policy "Email triage: owner insert"
    on public.email_triage for insert to authenticated
    with check (sales_id in (select id from public.sales where user_id = auth.uid()));
create policy "Email triage: owner update"
    on public.email_triage for update to authenticated
    using (sales_id in (select id from public.sales where user_id = auth.uid()))
    with check (sales_id in (select id from public.sales where user_id = auth.uid()));
create policy "Email triage: owner delete"
    on public.email_triage for delete to authenticated
    using (sales_id in (select id from public.sales where user_id = auth.uid()));
