-- Claim financials (Roadmap Stage 10 - Comptroller / Bookkeeper agent)
-- A money ledger per claim and a written-vs-settled record. Row Level
-- Security restricts these tables to finance roles (owner / accounting) and
-- administrators. Edge Function agents use the service role and are unaffected.

create table public.financial_ledger (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    deal_id bigint not null,
    entry_type text not null default 'payment_received',
    description text,
    amount numeric not null default 0,
    entry_date date,
    sales_id bigint
);

create table public.settlements (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    deal_id bigint not null,
    amount_written numeric,
    amount_settled numeric,
    settled_date date,
    notes text,
    sales_id bigint
);

alter table public.financial_ledger
    add constraint financial_ledger_deal_id_fkey foreign key (deal_id) references public.deals(id) on update cascade on delete cascade;
alter table public.financial_ledger
    add constraint financial_ledger_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.settlements
    add constraint settlements_deal_id_fkey foreign key (deal_id) references public.deals(id) on update cascade on delete cascade;
alter table public.settlements
    add constraint settlements_sales_id_fkey foreign key (sales_id) references public.sales(id);

create index financial_ledger_deal_id_idx on public.financial_ledger using btree (deal_id);
create unique index settlements_deal_id_idx on public.settlements using btree (deal_id);

create or replace trigger set_financial_ledger_sales_id_trigger
    before insert on public.financial_ledger
    for each row execute function public.set_sales_id_default();
create or replace trigger set_settlements_sales_id_trigger
    before insert on public.settlements
    for each row execute function public.set_sales_id_default();

-- Row Level Security: finance roles only.
alter table public.financial_ledger enable row level security;
alter table public.settlements enable row level security;

create policy "Finance role access" on public.financial_ledger
    for all to authenticated
    using (exists (select 1 from public.sales s where s.user_id = auth.uid() and (s.administrator or s.role in ('owner', 'accounting'))))
    with check (exists (select 1 from public.sales s where s.user_id = auth.uid() and (s.administrator or s.role in ('owner', 'accounting'))));

create policy "Finance role access" on public.settlements
    for all to authenticated
    using (exists (select 1 from public.sales s where s.user_id = auth.uid() and (s.administrator or s.role in ('owner', 'accounting'))))
    with check (exists (select 1 from public.sales s where s.user_id = auth.uid() and (s.administrator or s.role in ('owner', 'accounting'))));

grant all on table public.financial_ledger to anon, authenticated, service_role;
grant all on table public.settlements to anon, authenticated, service_role;
grant all on sequence public.financial_ledger_id_seq to anon, authenticated, service_role;
grant all on sequence public.settlements_id_seq to anon, authenticated, service_role;
