-- Documents & Email (Roadmap Stage 6 - Documents & Email agent)
-- Adds a text body to document templates so they can carry {{placeholder}}
-- tokens, and a table to log claim-related emails.

alter table public.document_templates add column body text;

create table public.claim_emails (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    deal_id bigint not null,
    direction text not null default 'inbound',
    from_email text,
    from_name text,
    to_email text,
    subject text,
    body text,
    received_at timestamp with time zone not null default now(),
    sales_id bigint
);

alter table public.claim_emails
    add constraint claim_emails_deal_id_fkey foreign key (deal_id) references public.deals(id) on update cascade on delete cascade;
alter table public.claim_emails
    add constraint claim_emails_sales_id_fkey foreign key (sales_id) references public.sales(id);

create index claim_emails_deal_id_idx on public.claim_emails using btree (deal_id);

create or replace trigger set_claim_emails_sales_id_trigger
    before insert on public.claim_emails
    for each row execute function public.set_sales_id_default();

alter table public.claim_emails enable row level security;
create policy "Enable all access for authenticated users" on public.claim_emails to authenticated using (true) with check (true);

grant all on table public.claim_emails to anon, authenticated, service_role;
grant all on sequence public.claim_emails_id_seq to anon, authenticated, service_role;
