-- Phase 10: Google Calendar integration.
-- Reuses the existing gmail_connections row (same Google account; the
-- OAuth flow now also requests calendar.events). calendar_events is
-- the per-firm projection: rows we either CREATED via
-- schedule-inspection or DISCOVERED via calendar-sync.

create table public.calendar_events (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),

    sales_id bigint not null references public.sales(id) on delete cascade,
    google_event_id text not null,
    google_calendar_id text not null default 'primary',
    ical_uid text,
    html_link text,

    summary text,
    description text,
    location text,
    starts_at timestamp with time zone,
    ends_at timestamp with time zone,
    all_day boolean default false,

    kind text check (
        kind in (
            'inspection',
            'reinspection',
            'appraisal',
            'mediation',
            'carrier_meeting',
            'insured_meeting',
            'deadline',
            'other'
        )
    ),

    -- AI-detected (or manually set) link to a claim.
    claim_id bigint references public.claims(id) on delete set null,
    -- nullable links for richer context, all set on creation or by sync.
    contact_id bigint references public.contacts(id) on delete set null,
    carrier_adjuster_id bigint references public.carrier_adjusters(id) on delete set null,

    status text not null default 'scheduled' check (
        status in ('scheduled', 'completed', 'cancelled', 'no_show')
    ),

    -- How the row got into the table: 'created' = we POSTed it via
    -- schedule-inspection; 'synced' = pulled from Google by
    -- calendar-sync.
    source text not null default 'created' check (source in ('created', 'synced')),

    ai_confidence numeric,
    ai_rationale text,
    notes text,

    unique (sales_id, google_event_id)
);

create index calendar_events_sales_id_idx on public.calendar_events using btree (sales_id);
create index calendar_events_claim_id_idx on public.calendar_events using btree (claim_id);
create index calendar_events_starts_at_idx on public.calendar_events using btree (starts_at);
create index calendar_events_status_idx on public.calendar_events using btree (status);

alter table public.calendar_events enable row level security;

-- Any authenticated user can READ (so a supervisor can see a colleague's
-- inspections); only the owning user can mutate their own rows.
create policy "Calendar events: authenticated read"
    on public.calendar_events for select to authenticated using (true);
create policy "Calendar events: owner insert"
    on public.calendar_events for insert to authenticated
    with check (sales_id in (select id from public.sales where user_id = auth.uid()));
create policy "Calendar events: owner update"
    on public.calendar_events for update to authenticated
    using (sales_id in (select id from public.sales where user_id = auth.uid()))
    with check (sales_id in (select id from public.sales where user_id = auth.uid()));
create policy "Calendar events: owner delete"
    on public.calendar_events for delete to authenticated
    using (sales_id in (select id from public.sales where user_id = auth.uid()));
