--
-- CARE claims intelligence
-- Tracks carriers, their adjusters, claims, estimates, and persisted policy
-- analyses so the firm can study how claims resolve over time.
--

create table public.carriers (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    name text not null,
    naic_code text,
    notes text,
    sales_id bigint
);

create table public.carrier_adjusters (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    carrier_id bigint,
    first_name text,
    last_name text,
    license_number text,
    license_state text,
    email text,
    phone text,
    notes text,
    sales_id bigint
);

create table public.claims (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    claim_number text,
    carrier_id bigint,
    carrier_adjuster_id bigint,
    deal_id bigint,
    contact_id bigint,
    policy_number text,
    loss_state text,
    date_of_loss date,
    peril text,
    status text not null default 'open',
    resolution_method text,
    resolved_at date,
    settlement_amount numeric(14, 2),
    attorney_involved boolean not null default false,
    mediation_representative text,
    notes text,
    sales_id bigint,
    constraint claims_status_check
        check (status in ('open', 'in_progress', 'resolved', 'closed')),
    constraint claims_resolution_method_check
        check (resolution_method is null or resolution_method in
            ('negotiation', 'appraisal', 'appraisal_award', 'mediation',
             'litigation', 'denied', 'withdrawn')),
    constraint claims_mediation_representative_check
        check (mediation_representative is null or mediation_representative in
            ('public_adjuster', 'attorney', 'none'))
);

create table public.claim_estimates (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    claim_id bigint not null,
    source text not null,
    amount numeric(14, 2),
    estimate_date date,
    software text,
    notes text,
    sales_id bigint,
    constraint claim_estimates_source_check
        check (source in ('carrier', 'public_adjuster', 'independent'))
);

create table public.policy_analyses (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    claim_id bigint,
    carrier_id bigint,
    policy_state text,
    model text,
    analysis jsonb not null,
    sales_id bigint
);

alter table public.carriers
    add constraint carriers_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.carrier_adjusters
    add constraint carrier_adjusters_carrier_id_fkey foreign key (carrier_id) references public.carriers(id) on delete set null;
alter table public.carrier_adjusters
    add constraint carrier_adjusters_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.claims
    add constraint claims_carrier_id_fkey foreign key (carrier_id) references public.carriers(id) on delete set null;
alter table public.claims
    add constraint claims_carrier_adjuster_id_fkey foreign key (carrier_adjuster_id) references public.carrier_adjusters(id) on delete set null;
alter table public.claims
    add constraint claims_deal_id_fkey foreign key (deal_id) references public.deals(id) on delete set null;
alter table public.claims
    add constraint claims_contact_id_fkey foreign key (contact_id) references public.contacts(id) on delete set null;
alter table public.claims
    add constraint claims_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.claim_estimates
    add constraint claim_estimates_claim_id_fkey foreign key (claim_id) references public.claims(id) on update cascade on delete cascade;
alter table public.claim_estimates
    add constraint claim_estimates_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.policy_analyses
    add constraint policy_analyses_claim_id_fkey foreign key (claim_id) references public.claims(id) on delete set null;
alter table public.policy_analyses
    add constraint policy_analyses_carrier_id_fkey foreign key (carrier_id) references public.carriers(id) on delete set null;
alter table public.policy_analyses
    add constraint policy_analyses_sales_id_fkey foreign key (sales_id) references public.sales(id);

create index carrier_adjusters_carrier_id_idx on public.carrier_adjusters using btree (carrier_id);
create index claims_carrier_id_idx on public.claims using btree (carrier_id);
create index claims_carrier_adjuster_id_idx on public.claims using btree (carrier_adjuster_id);
create index claims_deal_id_idx on public.claims using btree (deal_id);
create index claims_contact_id_idx on public.claims using btree (contact_id);
create index claim_estimates_claim_id_idx on public.claim_estimates using btree (claim_id);
create index policy_analyses_claim_id_idx on public.policy_analyses using btree (claim_id);
create index policy_analyses_carrier_id_idx on public.policy_analyses using btree (carrier_id);

--
-- Row Level Security
--
alter table public.carriers enable row level security;
alter table public.carrier_adjusters enable row level security;
alter table public.claims enable row level security;
alter table public.claim_estimates enable row level security;
alter table public.policy_analyses enable row level security;

-- Carriers
create policy "Enable read access for authenticated users" on public.carriers for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on public.carriers for insert to authenticated with check (true);
create policy "Enable update for authenticated users only" on public.carriers for update to authenticated using (true) with check (true);
create policy "Enable delete for authenticated users only" on public.carriers for delete to authenticated using (true);

-- Carrier Adjusters
create policy "Enable read access for authenticated users" on public.carrier_adjusters for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on public.carrier_adjusters for insert to authenticated with check (true);
create policy "Enable update for authenticated users only" on public.carrier_adjusters for update to authenticated using (true) with check (true);
create policy "Enable delete for authenticated users only" on public.carrier_adjusters for delete to authenticated using (true);

-- Claims
create policy "Enable read access for authenticated users" on public.claims for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on public.claims for insert to authenticated with check (true);
create policy "Enable update for authenticated users only" on public.claims for update to authenticated using (true) with check (true);
create policy "Enable delete for authenticated users only" on public.claims for delete to authenticated using (true);

-- Claim Estimates
create policy "Enable read access for authenticated users" on public.claim_estimates for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on public.claim_estimates for insert to authenticated with check (true);
create policy "Enable update for authenticated users only" on public.claim_estimates for update to authenticated using (true) with check (true);
create policy "Enable delete for authenticated users only" on public.claim_estimates for delete to authenticated using (true);

-- Policy Analyses
create policy "Enable read access for authenticated users" on public.policy_analyses for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on public.policy_analyses for insert to authenticated with check (true);
create policy "Enable update for authenticated users only" on public.policy_analyses for update to authenticated using (true) with check (true);
create policy "Enable delete for authenticated users only" on public.policy_analyses for delete to authenticated using (true);

--
-- Grants
--
grant all on table public.carriers to anon;
grant all on table public.carriers to authenticated;
grant all on table public.carriers to service_role;

grant all on table public.carrier_adjusters to anon;
grant all on table public.carrier_adjusters to authenticated;
grant all on table public.carrier_adjusters to service_role;

grant all on table public.claims to anon;
grant all on table public.claims to authenticated;
grant all on table public.claims to service_role;

grant all on table public.claim_estimates to anon;
grant all on table public.claim_estimates to authenticated;
grant all on table public.claim_estimates to service_role;

grant all on table public.policy_analyses to anon;
grant all on table public.policy_analyses to authenticated;
grant all on table public.policy_analyses to service_role;

grant all on sequence public.carriers_id_seq to anon;
grant all on sequence public.carriers_id_seq to authenticated;
grant all on sequence public.carriers_id_seq to service_role;

grant all on sequence public.carrier_adjusters_id_seq to anon;
grant all on sequence public.carrier_adjusters_id_seq to authenticated;
grant all on sequence public.carrier_adjusters_id_seq to service_role;

grant all on sequence public.claims_id_seq to anon;
grant all on sequence public.claims_id_seq to authenticated;
grant all on sequence public.claims_id_seq to service_role;

grant all on sequence public.claim_estimates_id_seq to anon;
grant all on sequence public.claim_estimates_id_seq to authenticated;
grant all on sequence public.claim_estimates_id_seq to service_role;

grant all on sequence public.policy_analyses_id_seq to anon;
grant all on sequence public.policy_analyses_id_seq to authenticated;
grant all on sequence public.policy_analyses_id_seq to service_role;
