-- Phase 14: storm verification records for wind/hail/tornado/hurricane
-- claims. Source-agnostic so the firm can mix HailTrace API results
-- with manual entries (CoreLogic, Verisk PCS, NOAA SPC, or a paper
-- meteorologist report uploaded as a PDF) without schema churn.

create table public.claim_storm_verifications (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),

    claim_id bigint not null references public.claims(id) on delete cascade,
    sales_id bigint references public.sales(id) on delete set null,

    source text not null check (
        source in ('hailtrace', 'corelogic', 'verisk_pcs', 'noaa_spc', 'manual', 'other')
    ),
    event_date date,                         -- when the storm occurred
    event_type text check (
        event_type in ('hail', 'wind', 'tornado', 'hurricane', 'flood', 'lightning', 'other')
    ),

    -- For hail
    hail_size_inches numeric,
    -- For wind
    wind_speed_mph numeric,
    wind_gust_mph numeric,
    -- For all events
    distance_miles numeric,                  -- distance from loss location
    confidence text check (confidence in ('high','medium','low','unknown')),

    -- Report storage
    report_url text,                         -- HailTrace / vendor report URL
    report_pdf_path text,                    -- Supabase storage path if PDF uploaded
    raw_response jsonb,                      -- whatever the API returned, for audit

    notes text,

    -- Verification status
    matches_loss_date boolean,               -- did the event fall on / near the DOL?
    matches_loss_location boolean,           -- did it hit the loss address?

    unique (claim_id, source, event_date)
);

create index storm_verifications_claim_id_idx
    on public.claim_storm_verifications using btree (claim_id);
create index storm_verifications_event_date_idx
    on public.claim_storm_verifications using btree (event_date);

alter table public.claim_storm_verifications enable row level security;

create policy "Storm verifications: authenticated read"
    on public.claim_storm_verifications for select to authenticated using (true);
create policy "Storm verifications: authenticated write"
    on public.claim_storm_verifications for all to authenticated
    using (true) with check (true);
