-- CARE multi-agent foundation (Roadmap Stage 1)
-- Adds the core data model the multi-agent system stands on:
--   * a role column on sales for firm-wide role-based access
--   * claim fields on the existing deals table (a "deal" is a claim)
--   * carriers + carrier_adjusters knowledge base
--   * policies attached to claims
--   * document_templates for the Documents agent
--   * task_templates + task_template_items for recurring/daily tasks
--   * agent_runs + agent_outputs to record what every agent does

-- ── Roles ────────────────────────────────────────────────────────────────────
-- owner | admin | adjuster | accounting | viewer (tightened by RLS in Stage 12)
alter table public.sales add column role text not null default 'adjuster';

-- ── Claim fields on the deals table ──────────────────────────────────────────
alter table public.deals add column claim_number text;
alter table public.deals add column date_of_loss date;
alter table public.deals add column loss_type text;
alter table public.deals add column loss_state text;
alter table public.deals add column loss_address text;
alter table public.deals add column loss_zipcode text;
alter table public.deals add column primary_carrier_id bigint;

-- ── Carriers ─────────────────────────────────────────────────────────────────
create table public.carriers (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    name text not null,
    naic_code text,
    phone text,
    email text,
    address text,
    claims_portal_url text,
    notes text,
    sales_id bigint
);

-- ── Carrier adjusters ────────────────────────────────────────────────────────
create table public.carrier_adjusters (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    carrier_id bigint,
    first_name text,
    last_name text,
    license_number text,
    license_state text,
    adjuster_type text,
    phone text,
    email text,
    notes text,
    sales_id bigint
);

-- ── Policies ─────────────────────────────────────────────────────────────────
create table public.policies (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    deal_id bigint not null,
    carrier_id bigint,
    policy_number text,
    named_insured text,
    policy_type text,
    effective_date date,
    expiration_date date,
    coverages jsonb not null default '{}'::jsonb,
    endorsements jsonb not null default '[]'::jsonb,
    exclusions jsonb not null default '[]'::jsonb,
    limits jsonb not null default '{}'::jsonb,
    deductibles jsonb not null default '{}'::jsonb,
    document_path text,
    sales_id bigint
);

-- ── Document templates ───────────────────────────────────────────────────────
create table public.document_templates (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    name text not null,
    description text,
    category text,
    file_path text,
    placeholders jsonb not null default '[]'::jsonb,
    sales_id bigint
);

-- ── Task templates ───────────────────────────────────────────────────────────
create table public.task_templates (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    name text not null,
    description text,
    cadence text not null default 'per_claim_stage',
    trigger_stage text,
    active boolean not null default true,
    sales_id bigint
);

create table public.task_template_items (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    template_id bigint not null,
    title text not null,
    description text,
    assignee_role text,
    offset_days integer not null default 0,
    sort_order integer not null default 0
);

-- ── Agent runs ───────────────────────────────────────────────────────────────
-- One row per agent invocation. The orchestrator run is the parent of the
-- specialist runs it delegates (parent_run_id).
create table public.agent_runs (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    deal_id bigint,
    parent_run_id bigint,
    agent_type text not null,
    status text not null default 'queued',
    triggered_by bigint,
    input jsonb not null default '{}'::jsonb,
    error text,
    model text,
    tokens_input integer,
    tokens_output integer,
    started_at timestamp with time zone,
    finished_at timestamp with time zone
);

-- ── Agent outputs ────────────────────────────────────────────────────────────
-- The deliverables agents produce (summaries, briefs, letters, reports).
-- Always created as a reviewable draft.
create table public.agent_outputs (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    run_id bigint,
    deal_id bigint,
    agent_type text not null,
    output_type text not null,
    title text,
    content text,
    data jsonb not null default '{}'::jsonb,
    status text not null default 'draft',
    reviewed_by bigint,
    sales_id bigint
);

-- ── Foreign keys ─────────────────────────────────────────────────────────────
alter table public.deals
    add constraint deals_primary_carrier_id_fkey foreign key (primary_carrier_id) references public.carriers(id) on delete set null;

alter table public.carriers
    add constraint carriers_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.carrier_adjusters
    add constraint carrier_adjusters_carrier_id_fkey foreign key (carrier_id) references public.carriers(id) on update cascade on delete cascade;
alter table public.carrier_adjusters
    add constraint carrier_adjusters_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.policies
    add constraint policies_deal_id_fkey foreign key (deal_id) references public.deals(id) on update cascade on delete cascade;
alter table public.policies
    add constraint policies_carrier_id_fkey foreign key (carrier_id) references public.carriers(id) on delete set null;
alter table public.policies
    add constraint policies_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.document_templates
    add constraint document_templates_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.task_templates
    add constraint task_templates_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.task_template_items
    add constraint task_template_items_template_id_fkey foreign key (template_id) references public.task_templates(id) on update cascade on delete cascade;

alter table public.agent_runs
    add constraint agent_runs_deal_id_fkey foreign key (deal_id) references public.deals(id) on update cascade on delete cascade;
alter table public.agent_runs
    add constraint agent_runs_parent_run_id_fkey foreign key (parent_run_id) references public.agent_runs(id) on delete set null;
alter table public.agent_runs
    add constraint agent_runs_triggered_by_fkey foreign key (triggered_by) references public.sales(id);

alter table public.agent_outputs
    add constraint agent_outputs_run_id_fkey foreign key (run_id) references public.agent_runs(id) on delete set null;
alter table public.agent_outputs
    add constraint agent_outputs_deal_id_fkey foreign key (deal_id) references public.deals(id) on update cascade on delete cascade;
alter table public.agent_outputs
    add constraint agent_outputs_reviewed_by_fkey foreign key (reviewed_by) references public.sales(id);
alter table public.agent_outputs
    add constraint agent_outputs_sales_id_fkey foreign key (sales_id) references public.sales(id);

-- ── Indexes on foreign keys ──────────────────────────────────────────────────
create index deals_primary_carrier_id_idx on public.deals using btree (primary_carrier_id);
create index carrier_adjusters_carrier_id_idx on public.carrier_adjusters using btree (carrier_id);
create index policies_deal_id_idx on public.policies using btree (deal_id);
create index policies_carrier_id_idx on public.policies using btree (carrier_id);
create index task_template_items_template_id_idx on public.task_template_items using btree (template_id);
create index agent_runs_deal_id_idx on public.agent_runs using btree (deal_id);
create index agent_runs_parent_run_id_idx on public.agent_runs using btree (parent_run_id);
create index agent_outputs_run_id_idx on public.agent_outputs using btree (run_id);
create index agent_outputs_deal_id_idx on public.agent_outputs using btree (deal_id);

-- ── Triggers: default sales_id from the current auth user on insert ──────────
create or replace trigger set_carriers_sales_id_trigger
    before insert on public.carriers
    for each row execute function public.set_sales_id_default();
create or replace trigger set_carrier_adjusters_sales_id_trigger
    before insert on public.carrier_adjusters
    for each row execute function public.set_sales_id_default();
create or replace trigger set_policies_sales_id_trigger
    before insert on public.policies
    for each row execute function public.set_sales_id_default();
create or replace trigger set_document_templates_sales_id_trigger
    before insert on public.document_templates
    for each row execute function public.set_sales_id_default();
create or replace trigger set_task_templates_sales_id_trigger
    before insert on public.task_templates
    for each row execute function public.set_sales_id_default();
create or replace trigger set_agent_outputs_sales_id_trigger
    before insert on public.agent_outputs
    for each row execute function public.set_sales_id_default();

-- ── Row Level Security ───────────────────────────────────────────────────────
-- Foundation tables: any authenticated firm user may read and write.
-- Stage 12 (Security agent) tightens this per role.
alter table public.carriers enable row level security;
alter table public.carrier_adjusters enable row level security;
alter table public.policies enable row level security;
alter table public.document_templates enable row level security;
alter table public.task_templates enable row level security;
alter table public.task_template_items enable row level security;
alter table public.agent_runs enable row level security;
alter table public.agent_outputs enable row level security;

create policy "Enable all access for authenticated users" on public.carriers to authenticated using (true) with check (true);
create policy "Enable all access for authenticated users" on public.carrier_adjusters to authenticated using (true) with check (true);
create policy "Enable all access for authenticated users" on public.policies to authenticated using (true) with check (true);
create policy "Enable all access for authenticated users" on public.document_templates to authenticated using (true) with check (true);
create policy "Enable all access for authenticated users" on public.task_templates to authenticated using (true) with check (true);
create policy "Enable all access for authenticated users" on public.task_template_items to authenticated using (true) with check (true);
create policy "Enable all access for authenticated users" on public.agent_runs to authenticated using (true) with check (true);
create policy "Enable all access for authenticated users" on public.agent_outputs to authenticated using (true) with check (true);

-- ── Grants ───────────────────────────────────────────────────────────────────
grant all on table public.carriers to anon, authenticated, service_role;
grant all on table public.carrier_adjusters to anon, authenticated, service_role;
grant all on table public.policies to anon, authenticated, service_role;
grant all on table public.document_templates to anon, authenticated, service_role;
grant all on table public.task_templates to anon, authenticated, service_role;
grant all on table public.task_template_items to anon, authenticated, service_role;
grant all on table public.agent_runs to anon, authenticated, service_role;
grant all on table public.agent_outputs to anon, authenticated, service_role;

grant all on sequence public.carriers_id_seq to anon, authenticated, service_role;
grant all on sequence public.carrier_adjusters_id_seq to anon, authenticated, service_role;
grant all on sequence public.policies_id_seq to anon, authenticated, service_role;
grant all on sequence public.document_templates_id_seq to anon, authenticated, service_role;
grant all on sequence public.task_templates_id_seq to anon, authenticated, service_role;
grant all on sequence public.task_template_items_id_seq to anon, authenticated, service_role;
grant all on sequence public.agent_runs_id_seq to anon, authenticated, service_role;
grant all on sequence public.agent_outputs_id_seq to anon, authenticated, service_role;
